apiVersion: v1
kind: Service
metadata:
  labels:
#    app: cassandra
    name: cassandra
  name: cassandra
  namespace: gridvo
spec:
  selector: 
#    app: cassandra
    name: cassandra
  clusterIP: 169.169.0.10
  ports:
     - port: 9042
       targetPort: 9042
#       protocol: TCP
