apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector: 
    app: kafka
  clusterIP: 169.169.0.9
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  - name: "9093"
    port: 9093
    targetPort: 9093
