apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
#    app: kafka
    name: kafka
  name: kafka
  namespace: gridvo
spec:
  replicas: 1
  template:
    metadata:
      labels:
#        app: kafka
        name: kafka
    spec:
      containers:
      - name: kafka
        image: 10.0.3.31:5000/wurstmeister/kafka:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9092
        - containerPort: 9093
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: 169.169.0.8:2181
#          value: zookeeper:2181
        - name: KAFKA_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: 169.169.0.9
#          value: kafka
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        volumeMounts:
        - name: sock
          mountPath: /var/run/docker.sock
      volumes:
      - name: sock
        hostPath:
          path: /var/run/docker.sock
