apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: 10.0.2.62:5000/mongo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
