apiVersion: v1
kind: Service
metadata:
  labels:
#    app: mongodb
    name: mongodb
  name: mongodb
  namespace: gridvo
spec:
  selector: 
#    app: mongodb
    name: mongodb
#  type: NodePort
  clusterIP: 169.169.0.7
  ports:
     - port: 27017
       targetPort: 27017
#       protocol: TCP
#       nodePort: 27017
