apiVersion: v1
kind: Service
metadata:
  name: zipkin
spec:
  selector: 
    app: zipkin
  type: NodePort
  ports:
  - name: "9410"
    port: 9410
    targetPort: 9410
    nodePort: 9410
  - name: "9411"
    port: 9411
    targetPort: 9411
    nodePort: 9411

