apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
#    app: zipkin-dependencies
    name: zipkin-dependencies
  name: zipkin-dependencies
  namespace: gridvo
spec:
  replicas: 1
  template:
    metadata:
      labels:
#        app: zipkin-dependencies
        name: zipkin-dependencies
    spec:
      containers:
      - name: zipkin-dependencies
        image: 10.0.3.31:5000/openzipkin/zipkin-dependencies
        imagePullPolicy: Always
        command:
           - crond
        args:
           - -f
        env:
        - name: STORAGE_TYPE
#          value: 169.169.0.10
          value: cassandra
        - name: CASSANDRA_CONTACT_POINTS
#          value: 169.169.0.10:9042
          value: cassandra:9042
