apiVersion: v1
kind: Service
metadata:
  labels:
#    app: zookeeper
    name: zookeeper
  name: zookeeper
  namespace: gridvo
spec:
  selector: 
#    app: zookeeper
    name: zookeeper
#  clusterIP: 169.169.0.8
  ports:
     - port: 2181
       targetPort: 2181
