apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: 10.0.2.62:5000/wurstmeister/zookeeper:latest
        ports:
        - containerPort: 2181
