apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
#    app: cassandra
    name: cassandra
  name: cassandra
  namespace: gridvo
spec:
  replicas: 1
  template:
    metadata:
      labels:
#        app: cassandra
        name: cassandra
    spec:
      containers:
      - name: cassandra
        image: 10.0.3.31:5000/openzipkin/zipkin-cassandra:1.18.0
        ports:
        - containerPort: 9042
