apiVersion: v1
kind: Service
metadata:
  labels:
#    app: kafka
    name: kafka
  name: kafka
  namespace: gridvo
spec:
  selector: 
#    app: kafka
    name: kafka
#  clusterIP: 10.10.201.9
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  - name: "9093"
    port: 9093
    targetPort: 9093
