apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
#    app: mongodb
    name: mongodb
  name: mongodb
  namespace: gridvo
spec:
  replicas: 1
  template:
    metadata:
      labels:
#        app: mongodb
        name: mongodb
    spec:
      containers:
      - name: mongodb
        image: 10.0.3.31:5000/mongo:latest
        ports:
        - containerPort: 27017
