apiVersion: v1
kind: Service
metadata:
  labels:
#    app: zipkin
    name: zipkin
  name: zipkin
  namespace: gridvo
spec:
  selector: 
#    app: zipkin
    name: zipkin
  type: NodePort
  ports:
  - name: "9410"
    port: 9410
    targetPort: 9410
    nodePort: 31010
  - name: "9411"
    port: 9411
    targetPort: 9411
    nodePort: 31011

