apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
#    app: zipkin
    name: zipkin
  name: zipkin
  namespace: gridvo
spec:
  replicas: 1
  template:
    metadata:
      labels:
#        app: zipkin
        name: zipkin
    spec:
      containers:
      - name: zipkin
        image: 10.0.3.31:5000/openzipkin/zipkin:1.18.0
        ports:
        - containerPort: 9410
        - containerPort: 9411
        env:
        - name: STORAGE_TYPE
          value: cassandra
        - name: CASSANDRA_CONTACT_POINTS
          value: cassandra:9042
