apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
#    app: zookeeper
    name: zookeeper
  name: zookeeper
  namespace: gridvo
spec:
  replicas: 1
  template:
    metadata:
      labels:
#        app: zookeeper
        name: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: 10.0.3.31:5000/wurstmeister/zookeeper:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 2181
